version: '3.4'

services:
  vclients.database:
    image: postgres:alpine3.18
    container_name: vclients.database
    environment:
      POSTGRES_DB: vclients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  vclients.api:
    image: ${DOCKER_REGISTRY-}vclientsapi
    container_name: vclients.api
    build:
      context: .
      dockerfile: VClients.Api/Dockerfile
    ports:
      - "5000:5000"
      #- "5001:5001"